// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
Delete From user_sessions
Where user_id = $1 AND token_hash = $2
`

type DeleteRefreshTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, arg.UserID, arg.TokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM person
WHERE id = $1 AND email = $2
`

type DeleteUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.Email)
	return err
}
