// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/pqtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO book(
    title,
    author,
    category,
    book_description
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, title
`

type CreateBookParams struct {
	Title           string `json:"title"`
	Author          string `json:"author"`
	Category        string `json:"category"`
	BookDescription string `json:"book_description"`
}

type CreateBookRow struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (CreateBookRow, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Category,
		arg.BookDescription,
	)
	var i CreateBookRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO person (
    user_role,
    user_name,
    surname,
    password_hash,
    email,
    remember,
    google_account
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id,email
`

type CreatePersonParams struct {
	UserRole      pqtype.NullRawMessage `json:"user_role"`
	UserName      string                `json:"user_name"`
	Surname       string                `json:"surname"`
	PasswordHash  string                `json:"password_hash"`
	Email         string                `json:"email"`
	Remember      bool                  `json:"remember"`
	GoogleAccount bool                  `json:"google_account"`
}

type CreatePersonRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (CreatePersonRow, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.UserRole,
		arg.UserName,
		arg.Surname,
		arg.PasswordHash,
		arg.Email,
		arg.Remember,
		arg.GoogleAccount,
	)
	var i CreatePersonRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO room(
    room_name,
    flor,
    n_seat
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateRoomParams struct {
	RoomName string `json:"room_name"`
	Flor     int32  `json:"flor"`
	NSeat    int32  `json:"n_seat"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.RoomName, arg.Flor, arg.NSeat)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSeat = `-- name: CreateSeat :one
INSERT INTO seat(
    room_id,
    seat_description
) VALUES (
    $1, $2
)
RETURNING id
`

type CreateSeatParams struct {
	RoomID          pgtype.UUID `json:"room_id"`
	SeatDescription string      `json:"seat_description"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSeat, arg.RoomID, arg.SeatDescription)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserBookBooking = `-- name: CreateUserBookBooking :one
INSERT INTO user_book_booking (
    book_id,
    user_id,
    reservation_date,
    expiration_date
) VALUES (
    $1, $2, $3, $4
)
RETURNING id,reservation_date,expiration_date
`

type CreateUserBookBookingParams struct {
	BookID          pgtype.UUID      `json:"book_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	ExpirationDate  pgtype.Timestamp `json:"expiration_date"`
}

type CreateUserBookBookingRow struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	ExpirationDate  pgtype.Timestamp `json:"expiration_date"`
}

func (q *Queries) CreateUserBookBooking(ctx context.Context, arg CreateUserBookBookingParams) (CreateUserBookBookingRow, error) {
	row := q.db.QueryRow(ctx, createUserBookBooking,
		arg.BookID,
		arg.UserID,
		arg.ReservationDate,
		arg.ExpirationDate,
	)
	var i CreateUserBookBookingRow
	err := row.Scan(&i.ID, &i.ReservationDate, &i.ExpirationDate)
	return i, err
}

const createUserBookManage = `-- name: CreateUserBookManage :one
INSERT INTO user_book_manage (
    book_id,
    user_id
) VALUES (
    $1, $2
)
RETURNING id
`

type CreateUserBookManageParams struct {
	BookID pgtype.UUID `json:"book_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateUserBookManage(ctx context.Context, arg CreateUserBookManageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserBookManage, arg.BookID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserRoomBooking = `-- name: CreateUserRoomBooking :one
INSERT INTO user_room_booking (
    reservation_date,
    room_id,
    user_id
) VALUES (
    $1, $2, $3
)
RETURNING id,reservation_date
`

type CreateUserRoomBookingParams struct {
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	RoomID          pgtype.UUID      `json:"room_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type CreateUserRoomBookingRow struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
}

func (q *Queries) CreateUserRoomBooking(ctx context.Context, arg CreateUserRoomBookingParams) (CreateUserRoomBookingRow, error) {
	row := q.db.QueryRow(ctx, createUserRoomBooking, arg.ReservationDate, arg.RoomID, arg.UserID)
	var i CreateUserRoomBookingRow
	err := row.Scan(&i.ID, &i.ReservationDate)
	return i, err
}

const createUserSeatBooking = `-- name: CreateUserSeatBooking :one
INSERT INTO user_seat_booking (
    reservation_date,
    seat_id,
    user_id
) VALUES (
    $1, $2, $3
)
RETURNING id,reservation_date
`

type CreateUserSeatBookingParams struct {
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	SeatID          pgtype.UUID      `json:"seat_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type CreateUserSeatBookingRow struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
}

func (q *Queries) CreateUserSeatBooking(ctx context.Context, arg CreateUserSeatBookingParams) (CreateUserSeatBookingRow, error) {
	row := q.db.QueryRow(ctx, createUserSeatBooking, arg.ReservationDate, arg.SeatID, arg.UserID)
	var i CreateUserSeatBookingRow
	err := row.Scan(&i.ID, &i.ReservationDate)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO user_sessions(
    user_id,
    token_hash,
    user_agent,
    ip_address,
    is_revoked,
    expires_at,
    created_at
)VALUES(
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	IsRevoked bool               `json:"is_revoked"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.IsRevoked,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
