// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TypeRole string

const (
	TypeRoleStudent   TypeRole = "student"
	TypeRoleTeacher   TypeRole = "teacher"
	TypeRoleLibrarian TypeRole = "librarian"
	TypeRoleAdmin     TypeRole = "admin"
)

func (e *TypeRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeRole(s)
	case string:
		*e = TypeRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeRole: %T", src)
	}
	return nil
}

type NullTypeRole struct {
	TypeRole TypeRole `json:"type_role"`
	Valid    bool     `json:"valid"` // Valid is true if TypeRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeRole) Scan(value interface{}) error {
	if value == nil {
		ns.TypeRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeRole), nil
}

type Book struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Author          string      `json:"author"`
	Category        string      `json:"category"`
	BookDescription string      `json:"book_description"`
}

type Person struct {
	ID       pgtype.UUID `json:"id"`
	UserRole TypeRole    `json:"user_role"`
	UserName string      `json:"user_name"`
	Surname  string      `json:"surname"`
}

type Room struct {
	ID       pgtype.UUID `json:"id"`
	RoomName string      `json:"room_name"`
	Flor     int32       `json:"flor"`
	NSeat    int32       `json:"n_seat"`
}

type Seat struct {
	ID              pgtype.UUID `json:"id"`
	RoomID          pgtype.UUID `json:"room_id"`
	SeatDescription string      `json:"seat_description"`
}

type UserBookBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	ExpirationDate  pgtype.Timestamp `json:"expiration_date"`
	BookID          pgtype.UUID      `json:"book_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type UserBookManage struct {
	ID     pgtype.UUID `json:"id"`
	BookID pgtype.UUID `json:"book_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type UserRoomBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	RoomID          pgtype.UUID      `json:"room_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type UserSeatBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	SeatID          pgtype.UUID      `json:"seat_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}
