// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/pqtype"
)

type Book struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Author          string      `json:"author"`
	Category        string      `json:"category"`
	BookDescription string      `json:"book_description"`
}

type Organization struct {
	ID               pgtype.UUID           `json:"id"`
	NameOrganization string                `json:"name_organization"`
	AdminID          pgtype.UUID           `json:"admin_id"`
	RoleName         pqtype.NullRawMessage `json:"role_name"`
}

type Person struct {
	ID            pgtype.UUID           `json:"id"`
	UserName      string                `json:"user_name"`
	UserRole      pqtype.NullRawMessage `json:"user_role"`
	Surname       string                `json:"surname"`
	PasswordHash  string                `json:"password_hash"`
	Email         string                `json:"email"`
	Remember      bool                  `json:"remember"`
	GoogleAccount bool                  `json:"google_account"`
}

type Room struct {
	ID       pgtype.UUID `json:"id"`
	RoomName string      `json:"room_name"`
	Flor     int32       `json:"flor"`
	NSeat    int32       `json:"n_seat"`
}

type Seat struct {
	ID              pgtype.UUID `json:"id"`
	RoomID          pgtype.UUID `json:"room_id"`
	SeatDescription string      `json:"seat_description"`
}

type UserBookBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	ExpirationDate  pgtype.Timestamp `json:"expiration_date"`
	BookID          pgtype.UUID      `json:"book_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type UserBookManage struct {
	ID     pgtype.UUID `json:"id"`
	BookID pgtype.UUID `json:"book_id"`
	UserID pgtype.UUID `json:"user_id"`
}

type UserRoomBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	RoomID          pgtype.UUID      `json:"room_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type UserSeatBooking struct {
	ID              pgtype.UUID      `json:"id"`
	ReservationDate pgtype.Timestamp `json:"reservation_date"`
	SeatID          pgtype.UUID      `json:"seat_id"`
	UserID          pgtype.UUID      `json:"user_id"`
}

type UserSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	IsRevoked bool               `json:"is_revoked"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
