// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (CreateBookRow, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (CreatePersonRow, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (pgtype.UUID, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (pgtype.UUID, error)
	CreateUserBookBooking(ctx context.Context, arg CreateUserBookBookingParams) (CreateUserBookBookingRow, error)
	CreateUserBookManage(ctx context.Context, arg CreateUserBookManageParams) (pgtype.UUID, error)
	CreateUserRoomBooking(ctx context.Context, arg CreateUserRoomBookingParams) (CreateUserRoomBookingRow, error)
	CreateUserSeatBooking(ctx context.Context, arg CreateUserSeatBookingParams) (CreateUserSeatBookingRow, error)
	DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetAllFromBooks(ctx context.Context) ([]Book, error)
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (GetRefreshTokenRow, error)
	GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (GetRefreshTokenByHashRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserbyId(ctx context.Context, id pgtype.UUID) (GetUserbyIdRow, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	UpdateRemember(ctx context.Context, arg UpdateRememberParams) error
}

var _ Querier = (*Queries)(nil)
