// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (CreateBookRow, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (CreatePersonRow, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (pgtype.UUID, error)
	CreateSeat(ctx context.Context, arg CreateSeatParams) (pgtype.UUID, error)
	CreateUserBookBooking(ctx context.Context, arg CreateUserBookBookingParams) (CreateUserBookBookingRow, error)
	CreateUserBookManage(ctx context.Context, arg CreateUserBookManageParams) (pgtype.UUID, error)
	CreateUserRoomBooking(ctx context.Context, arg CreateUserRoomBookingParams) (CreateUserRoomBookingRow, error)
	CreateUserSeatBooking(ctx context.Context, arg CreateUserSeatBookingParams) (CreateUserSeatBookingRow, error)
	GetAllFromBooks(ctx context.Context) ([]Book, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
