// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select.sql

package sqlc

import (
	"context"
)

const getAllFromBooks = `-- name: GetAllFromBooks :many
SELECT id, title, author, category, book_description FROM book
`

func (q *Queries) GetAllFromBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getAllFromBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.BookDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
