// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllFromBooks = `-- name: GetAllFromBooks :many
SELECT id, title, author, category, book_description FROM book
`

func (q *Queries) GetAllFromBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, getAllFromBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Category,
			&i.BookDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
Select id,token_hash
From user_sessions 
Where user_id = $1 AND is_revoked = $2
`

type GetRefreshTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IsRevoked bool        `json:"is_revoked"`
}

type GetRefreshTokenRow struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, arg.UserID, arg.IsRevoked)
	var i GetRefreshTokenRow
	err := row.Scan(&i.ID, &i.TokenHash)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
Select u_s.id,u_s.token_hash,p.id,p.user_name,p.surname,p.email
From user_sessions as u_s,person as p
Where u_s.user_id = p.id AND u_s.token_hash = $1 AND u_s.is_revoked = $2
`

type GetRefreshTokenByHashParams struct {
	TokenHash string `json:"token_hash"`
	IsRevoked bool   `json:"is_revoked"`
}

type GetRefreshTokenByHashRow struct {
	ID        pgtype.UUID `json:"id"`
	TokenHash string      `json:"token_hash"`
	ID_2      pgtype.UUID `json:"id_2"`
	UserName  string      `json:"user_name"`
	Surname   string      `json:"surname"`
	Email     string      `json:"email"`
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, arg.TokenHash, arg.IsRevoked)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ID_2,
		&i.UserName,
		&i.Surname,
		&i.Email,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, google_account
FROM person
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID            pgtype.UUID `json:"id"`
	Email         string      `json:"email"`
	PasswordHash  string      `json:"password_hash"`
	GoogleAccount bool        `json:"google_account"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleAccount,
	)
	return i, err
}

const getUserbyId = `-- name: GetUserbyId :one
Select user_name,surname 
From person 
Where id = $1
`

type GetUserbyIdRow struct {
	UserName string `json:"user_name"`
	Surname  string `json:"surname"`
}

func (q *Queries) GetUserbyId(ctx context.Context, id pgtype.UUID) (GetUserbyIdRow, error) {
	row := q.db.QueryRow(ctx, getUserbyId, id)
	var i GetUserbyIdRow
	err := row.Scan(&i.UserName, &i.Surname)
	return i, err
}
