// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateRemember = `-- name: UpdateRemember :exec
UPDATE person
SET remember = $1
WHERE id = $2 AND email = $3
`

type UpdateRememberParams struct {
	Remember bool        `json:"remember"`
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdateRemember(ctx context.Context, arg UpdateRememberParams) error {
	_, err := q.db.Exec(ctx, updateRemember, arg.Remember, arg.ID, arg.Email)
	return err
}
